import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  coreSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introdução ao Curso',
    },
    {
      type: 'autogenerated',
      dirName: 'core',
    },
  ],
  backendSidebar: [
    {
      type: 'autogenerated',
      dirName: 'backend',
    },
  ],
  frontendSidebar: [
    {
      type: 'autogenerated',
      dirName: 'frontend',
    },
  ],
};

export default sidebars;
